"""The block catalogue, loaded once from the generated table.

Everything downstream — items, locations, rules — reads from here, so there is
exactly one place where "which blocks exist" is answered. The table itself is
generated by tools/generate_block_table.py from the game's own enum; nothing
in this package types a block name by hand.
"""
from __future__ import annotations

import json
import pkgutil
from typing import NamedTuple


class Block(NamedTuple):
    id: str        # the game's own BlockTypes name, e.g. GSOFuelTank_121
    name: str      # player-facing, e.g. "GSO Fuel Tank"
    corp: str      # "GSO", "GeoCorp", ...
    corp_key: str  # "GSO", "GC", ...
    tier: int      # 1-5, the licence grade


def _load() -> tuple[list[Block], dict]:
    # pkgutil, not pathlib: an installed apworld is a ZIP, and __file__ points
    # at a path inside it that the filesystem cannot open. This is the one
    # thing that separates "works from source" from "works when shipped".
    blob = pkgutil.get_data(__name__, "data/blocks.json")
    if blob is None:
        raise FileNotFoundError("terratech: data/blocks.json is missing from the apworld")
    raw = json.loads(blob.decode("utf-8"))
    blocks = [Block(b["id"], b["name"], b["corp"], b["corp_key"], b["tier"])
              for b in raw["blocks"]]
    return blocks, raw


BLOCKS, _RAW = _load()
BLOCK_BY_NAME = {b.name: b for b in BLOCKS}
BLOCK_BY_ID = {b.id: b for b in BLOCKS}

CORPORATIONS = sorted({b.corp for b in BLOCKS})
TIERS = (1, 2, 3, 4, 5)

# Corporations that exist in the game's enum but carry no blocks of their own
# in this build. Recorded rather than dropped silently, so a future game
# update that adds them is a data change and not a mystery.
CORPS_WITHOUT_BLOCKS = ("Reticule Research", "Legion")

# The starter pool is the two corporations a campaign actually begins with.
STARTER_CORPS = ("GSO", "Space Junkers")


def blocks_for_pool(pool: str) -> list[Block]:
    """Which blocks a seed shuffles, per the block_pool option."""
    if pool == "starter":
        return [b for b in BLOCKS if b.corp in STARTER_CORPS]
    if pool == "standard":
        return [b for b in BLOCKS if b.tier <= 3]
    return list(BLOCKS)


def blocks_by_tier(blocks: list[Block]) -> dict[int, list[Block]]:
    out: dict[int, list[Block]] = {t: [] for t in TIERS}
    for b in blocks:
        out[b.tier].append(b)
    return out


# How many carrier locations sit in each grade, as a share of the total the
# player asked for. Early grades hold more because that is where the player
# spends most of the run; grade 5 is a short, expensive tail.
TIER_WEIGHTS = {1: 0.30, 2: 0.25, 3: 0.20, 4: 0.15, 5: 0.10}

# Vanilla price multipliers per grade, used to describe shop locations. These
# are the design's own numbers, not read from the game -- the mod applies the
# real vanilla price and this is only how the location is labelled.
TIER_PRICE_LABEL = {1: "cheap", 2: "x3", 3: "x8", 4: "x20", 5: "x50"}

# Kill and gather milestones. Each one is a location, fired once.
QUEST_MILESTONES = (5, 10, 25, 50, 100, 200, 350, 500, 750, 1000)

# The campaign missions the game ships, as location names. ⚠ These are the
# mission TYPES read out of the assembly (432 of them, of which these are the
# licence-bearing and set-piece ones). The mod matches on the mission's own
# id, so a name that drifts in a game update shows up as a warning rather than
# a silently missing location.
CAMPAIGN_MISSIONS = tuple(
    f"Mission {i:03d}" for i in range(1, 151)
)


def split_by_tier(total: int) -> dict[int, int]:
    """Spread a carrier count across the five grades by TIER_WEIGHTS.

    Remainders land in grade 1: rounding down everywhere would quietly lose
    locations, and losing locations means a seed that cannot be completed.
    """
    out = {t: int(total * TIER_WEIGHTS[t]) for t in TIERS}
    out[1] += total - sum(out.values())
    return out
